# Generated by Django 4.1.3 on 2022-11-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_course_lessons_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default='new', upload_to='lesson-images'),
            preserve_default=False,
        ),
    ]
