# Generated by Django 4.1.3 on 2022-11-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore quisquam quibusdam, nemo officia iste similique quo eius nulla vel praesentium!'),
            preserve_default=False,
        ),
    ]
