# Generated by Django 4.1.3 on 2022-11-30 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wysiwyg_img', '0001_initial'),
        ('core', '0006_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('baseimagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wysiwyg_img.baseimagemodel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
            bases=('wysiwyg_img.baseimagemodel',),
        ),
    ]
